channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.0.0
  - numpy==1.26.0
  - pandas==2.1.1
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.13.1
name: mlflow-env
